import QtQuick

Item
{
    property color colorBrightText   : "#FFFFFF"
    property color colorLightText    : "#8E8EA9"
    property color colorLightText2   : "#8A8AA0"
    property color colorLightText3   : "#666687"
    property color colorBasePurple   : "#946BDE"
    property color colorMediumPurple : "#D9D8FF"
    property color colorPinkPurple   : "#E3D6FF"
    property color colorLightPurple  : "#F0F0FF"
    property color colorLightGray    : "#F6F6F9"
    property color colorLightGray2   : "#EDEDED"
    property color colorLightGray3   : "#E2E2E2"
    property color colorNeonBlue     : "#4945FF"
    property color colorLightGreen   : "#EAFBE7"
    property color colorLightGreen2  : "#C6F0C2"
    property color colorMediumGreen  : "#5CB176"
    property color colorCoffeeBrown  : "#E79535"
    property color colorBaseText     : "#32324D"
    property color colorBaseTitle    : "#4A4A6A"
    property color colorMediumText   : "#505057"
    property color colorLightBorder  : "#DCDCE4"
    property color colorLightBorder2 : "#C0C0CF"
    property color colorLightBorder3 : "#E0E0DE"
    property color colorBaseGray     : "#D2D2D2"
    property color colorDarkBorder   : "#ADADB4"
    property color colorError        : "#DC4446"
    property color colorBackground   : "#FFFFFF"
    property color darkBackground    : "#CCCCCC"
    property color colorSidebarMark  : "#F0F0FF"
    property color colorSeparator    : "#EAEAEF"
    property color loginWindowBackground  : "#efefef"
    property color loginContentBackground : "white"
    property color colorLightGrayBackground : "#EAEAEF"
    property color pagesBackground: "#F6F6F9"
    
    property string defaultFontFamily : "SF Pro Display"
    
    
    // Arrows-icons
    property string iconArrowDownBlack: "/resources/images/arrows/arrow_down_black_icon.svg"
    property string iconArrowtopBlackRight: "/resources/images/arrows/arrowtop_black_right_icon.svg"
    property string iconArrowtopGrayRight: "/resources/images/arrows/arrowtop_gray_right_icon.svg"
    property string iconDropdownBlack: "/resources/images/arrows/dropdown_black_icon.svg"
    property string iconDropDownGray: "/resources/images/arrows/dropdown_gray_icon.svg"
    property string iconDropupLightGray: "/resources/images/arrows/dropup_lightgray_icon.svg"
    
    // Decision-icons
    property string iconCheckBlackThin: "/resources/images/decision/check_black_thin_icon.svg"
    property string iconCheckGreen : "/resources/images/decision/check_green_icon.svg"
    property string iconCheckWhite : "/resources/images/decision/check_white_icon.svg"
    property string iconCloseBlack : "/resources/images/decision/close_black_icon.svg"
    property string iconClosePurple : "/resources/images/decision/close_purple_icon.svg"
    property string iconPlusBlack : "/resources/images/decision/plus_black_icon.svg"
    property string iconPlusPurple : "/resources/images/decision/plus_purple_icon.svg"
    property string iconPlusWhite : "/resources/images/decision/plus_white_icon.svg"
    
    // Decoration-icons
    property string iconCoffee : "/resources/images/decoration/coffee_icon.svg"
    property string iconHeartGray : "/resources/images/decoration/heart_gray_icon.svg"
    property string iconHeartWhiteHallow : "/resources/images/decoration/heart_white_hallow_icon.svg"
    property string iconSeed : "/resources/images/decoration/seed_icon.svg"
    
    // Illustrations
    property string illustrationAddImage : "/resources/images/illustrations/add_image_illustration.svg"
    property string illustrationBookCover : "/resources/images/illustrations/book_cover.png"
    property string illustrationEmptyHomeBackground : "/resources/images/illustrations/empty_home_background.svg"
    property string illustrationEyeCrossedSwift : "/resources/images/illustrations/eye_crossed_illustration.png"
    property string illustrationFileSwift : "/resources/images/illustrations/file_swift_illustration.svg"
    
    // ReadingView-icons
    property string iconArrowBlackHallowThin : "/resources/images/readingView/arrowtop_black_left_thin_icon.svg"
    property string iconArrowPurpleHallowThin : "/resources/images/readingView/arrowtop_purple_left_thin_icon.svg"
    property string iconReadingViewBookmarkBlack : "/resources/images/readingView/bookmark_black_icon.svg"
    property string iconReadingViewBookmarkPurple : "/resources/images/readingView/bookmark_purple_icon.svg"
    property string iconReadingViewMaximizeBlack : "/resources/images/readingView/maximize_black_icon.svg"
    property string iconReadingViewMaximizePurple : "/resources/images/readingView/maximize_purple_icon.svg"
    property string iconReadingViewMenuBlack : "/resources/images/readingView/menu_black_icon.svg"
    property string iconReadingViewMenuPurple : "/resources/images/readingView/menu_purple_icon.svg"
    property string iconReadingViewSearchBlackThin : "/resources/images/readingView/search_black_thin_icon.svg"
    property string iconReadingViewSearchPurpleThin : "/resources/images/readingView/search_purple_thin_icon.svg"
    property string iconReadingViewSidebarBlack : "/resources/images/readingView/sidebar_black_icon.svg"
    property string iconReadingViewSidebarPurple : "/resources/images/readingView/purple_purple_icon.svg"
    
    // Setting-icons
    property string iconSettingsAboutGray : "/resources/images/settings/about_gray_icon.svg"
    property string iconSettingsAboutPurple : "/resources/images/settings/about_purple_icon.svg"
    property string iconSettingsAccountGray : "/resources/images/settings/account_gray_icon.svg"
    property string iconSettingsAccountPurple : "/resources/images/settings/account_purple_icon.svg"
    property string iconSettingsAppearanceGray : "/resources/images/settings/appearance_gray_icon.svg"
    property string iconSettingsAppearancePurple : "/resources/images/settings/appearance_purple_icon.svg"
    property string iconSettingsSettingsGray : "/resources/images/settings/settings_gray_icon.svg"
    property string iconSettingsSettingsPurple : "/resources/images/settings/settings_purple_icon.svg"
    property string iconSettingsShortcutsGray : "/resources/images/settings/shortcuts_gray_icon.svg"
    property string iconSettingsShortcutsPurple : "/resources/images/settings/shortcuts_purple_icon.svg"
    property string iconSettingsStorageGray : "/resources/images/settings/storage_gray_icon.svg"
    property string iconSettingsStoragePurple : "/resources/images/settings/storage_purple_icon.svg"
    property string iconSettingsSupportUsGray : "/resources/images/settings/support_us_gray_icon.svg"
    property string iconSettingsSupportUsPurple : "/resources/images/settings/support_us_purple_icon.svg"
    property string iconSettingsUpdatesGray : "/resources/images/settings/updates_gray_icon.svg"
    property string iconSettingsUpdatesPurple : "/resources/images/settings/updates_purple_icon.svg"
    
    // Sidebar-icons
    property string iconEmptyProfile : "/resources/images/sidebar/empty_profile_icon.svg"
    property string iconHome: "/resources/images/sidebar/home_icon.svg"
    property string iconPieChart: "/resources/images/sidebar/pieChart_icon.svg"
    property string iconTool: "/resources/images/sidebar/wrench_icon.svg"
    property string iconSettings: "/resources/images/sidebar/settings_icon.svg"
    property string iconAddOns: "/resources/images/sidebar/puzzle_icon.svg"
    
    // Utility-icons
    property string iconDots : "/resources/images/utility/dots_icon.svg"
    property string iconDownloadGray : "/resources/images/utility/download_gray_icon.svg"
    property string iconDownloadWhite: "/resources/images/utility/download_white_icon.svg"
    property string iconEdit : "/resources/images/utility/edit_icon.svg"
    property string iconEyeOff : "/resources/images/utility/eye_off_icon.svg"
    property string iconEyeOn : "/resources/images/utility/eye_on_icon.svg"
    property string iconFilter : "/resources/images/utility/filter_icon.svg"
    property string iconLogout : "/resources/images/utility/log_out_icon.svg"
    property string iconSearch : "/resources/images/utility/search_icon.svg"
    property string iconSync : "/resources/images/utility/sync_icon.svg"
    property string iconTag : "/resources/images/utility/tag_icon.svg"
    property string iconTrash : "/resources/images/utility/trash_icon.svg"
    
    
    property string currentVersion   : "v0.0.1 - alpha"
    property string newestVersion    : "v1.14.3"
    property string currentQtVersion : "v6.2.2"
    property string companyName    : "Etovex"
    property string companyWebsite : "www.etovex.com"
    property string companyEmail   : "support@etovex.com"
}