import QtQuick

Item
{
    property color colorBrightText   : "#FFFFFF"
    property color colorLightText    : "#8E8EA9"
    property color colorLightText2   : "#8A8AA0"
    property color colorLightText3   : "#666687"
    property color colorBasePurple   : "#946BDE"
    property color colorMediumPurple : "#D9D8FF"
    property color colorPinkPurple   : "#E3D6FF"
    property color colorLightPurple  : "#F0F0FF"
    property color colorLightGray    : "#F6F6F9"
    property color colorLightGray2   : "#EDEDED"
    property color colorNeonBlue     : "#4945FF"
    property color colorLightGreen   : "#EAFBE7"
    property color colorLightGreen2  : "#C6F0C2"
    property color colorMediumGreen  : "#5CB176"
    property color colorCoffeeBrown  : "#E79535"
    property color colorBaseText     : "#32324D"
    property color colorBaseTitle    : "#4A4A6A"
    property color colorMediumText   : "#505057"
    property color colorLightBorder  : "#DCDCE4"
    property color colorLightBorder2 : "#C0C0CF"
    property color colorLightBorder3 : "#E0E0DE"
    property color colorBaseGray     : "#D2D2D2"
    property color colorDarkBorder   : "#ADADB4"
    property color colorError        : "#DC4446"
    property color colorBackground   : "#FFFFFF"
    property color darkBackground    : "#CCCCCC"
    property color colorSidebarMark  : "#F0F0FF"
    property color colorSeparator    : "#EAEAEF"
    property color loginWindowBackground  : "#efefef"
    property color loginContentBackground : "white"
    property color colorLightGrayBackground : "#EAEAEF"
    property color pagesBackground: "#F6F6F9"
    
    
    property string defaultFontFamily : "SF Pro Display"
    
    
    property string iconHome : "/resources/images/home_icon.svg"
    property string iconDownload : "/resources/images/download_icon.svg"
    property string iconDownloadWhite: "/resources/images/download_icon_white.svg"
    property string iconPieChart : "/resources/images/pieChart_icon.svg"
    property string iconTool : "/resources/images/wrench_icon.svg"
    property string iconAddOns : "/resources/images/puzzle_icon.svg"
    property string iconSettings : "/resources/images/settings_icon.svg"
    property string iconEyeOn : "/resources/images/eye_on_icon.svg"
    property string iconEyeOff : "/resources/images/eye_off_icon.svg"
    property string iconCheckLong : "/resources/images/check_long_icon.svg"
    property string iconSearch : "/resources/images/search_icon.svg"
    property string iconDots : "/resources/images/dots_icon.svg"
    property string iconArrowRightHallow : "/resources/images/arrow_hallow_right_icon.svg"
    property string iconArrowDownFilled : "/resources/images/arrow_filled_down_icon.svg"
    property string iconArrowGrayRightFilled : "/resources/images/arrow_gray_hallow_right_icon.svg"
    property string iconArrowUpFilled : "/resources/images/arrow_filled_up_icon.svg"
    property string iconPlusWhite : "/resources/images/plus_white_icon.svg"
    property string iconPlusBlack : "/resources/images/plus_black_icon.svg"
    property string iconPlusPurple : "/resources/images/plus_purple_icon.svg"
    property string iconTag : "/resources/images/tag_icon.svg"
    property string iconFilter : "/resources/images/filter_icon.svg"
    property string iconSync : "/resources/images/sync_icon.svg"
    property string iconEmptyProfile : "/resources/images/empty_profile_background.svg"
    property string iconLogout : "/resources/images/log_out_icon.svg"
    property string iconCheckGreen : "/resources/images/check_green_icon.svg"
    property string iconCheckWhite : "/resources/images/check_white_icon.svg"
    property string iconHeartGray : "/resources/images/heart_gray_icon.svg"
    property string iconHeartWhite : "/resources/images/heart_white_icon.svg"
    property string iconSeed : "/resources/images/seed_icon.svg"
    property string iconCoffee : "/resources/images/coffee_icon.svg"
    property string iconArrowDownHallow : "/resources/images/arrow_down_hallow_icon.svg"
    property string iconAddImage : "/resources/images/add_image_icon.svg"
    property string iconTrash : "/resources/images/trash_icon.svg"
    property string iconEdit : "/resources/images/edit_icon.svg"
    property string iconClosePurple : "/resources/images/close_purple_icon.svg"
    property string iconCloseBlack : "/resources/images/close_black_icon.svg"
    property string iconDropDownBlack : "/resources/images/dropdown_black_icon.svg"
    
    property string iconSettingsAboutGray : "/resources/images/settings/about_gray.svg"
    property string iconSettingsShortcutsGray : "/resources/images/settings/shortcuts_gray.svg"
    property string iconSettingsAccountGray : "/resources/images/settings/account_gray.svg"
    property string iconSettingsAppearanceGray : "/resources/images/settings/appearance_gray.svg"
    property string iconSettingsSettingsGray : "/resources/images/settings/settings_gray.svg"
    property string iconSettingsStorageGray : "/resources/images/settings/storage_gray.svg"
    property string iconSettingsSupportUsGray : "/resources/images/settings/support_us_gray.svg"
    property string iconSettingsUpdatesGray : "/resources/images/settings/updates_gray.svg"
    property string iconSettingsAboutPurple : "/resources/images/settings/about_purple.svg"
    property string iconSettingsShortcutsPurple : "/resources/images/settings/shortcuts_purple.svg"
    property string iconSettingsAccountPurple : "/resources/images/settings/account_purple.svg"
    property string iconSettingsAppearancePurple : "/resources/images/settings/appearance_purple.svg"
    property string iconSettingsSettingsPurple : "/resources/images/settings/settings_purple.svg"
    property string iconSettingsStoragePurple : "/resources/images/settings/storage_purple.svg"
    property string iconSettingsSupportUsPurple : "/resources/images/settings/support_us_purple.svg"
    property string iconSettingsUpdatesPurple : "/resources/images/settings/updates_purple.svg"
    
    property string iconArrowBlackHallowThin : "/resources/images/readingView/arrow_black_hallow_left_thin_icon.svg"
    property string iconArrowPurpleHallowThin : "/resources/images/readingView/arrow_purple_hallow_left_thin_icon.svg"
    property string iconBookmarkBlack : "/resources/images/readingView/bookmark_black_icon.svg"
    property string iconBookmarkPurple : "/resources/images/readingView/bookmark_purple_icon.svg"
    property string iconMaximizeBlack : "/resources/images/readingView/maximize_black_icon.svg"
    property string iconMaximizePurple : "/resources/images/readingView/maximize_purple_icon.svg"
    property string iconMenuBlack : "/resources/images/readingView/menu_black_icon.svg"
    property string iconMenuPurple : "/resources/images/readingView/menu_purple_icon.svg"
    property string iconSearchBlackThin : "/resources/images/readingView/search_black_thin_icon.svg"
    property string iconSearchPurpleThin : "/resources/images/readingView/search_purple_thin_icon.svg"
    property string iconSidebarBlack : "/resources/images/readingView/sidebar_black_icon.svg"
    property string iconSidebarPurple : "/resources/images/readingView/purple_purple_icon.svg"
    
    property string imageBookCover : "/resources/images/book_cover.png"
    property string imageEmptyHomeBackground : "/resources/images/empty_home_background.svg"
    property string imageEyeCrossedSwift : "/resources/images/eye_crossed_image.png"
    property string imageFileSwift : "/resources/images/file_swift.svg"
    
    property string currentVersion   : "v0.0.1 - alpha"
    property string newestVersion    : "v1.14.3"
    property string currentQtVersion : "v6.2.2"
    property string companyName    : "Etovex"
    property string companyWebsite : "www.etovex.com"
    property string companyEmail   : "support@etovex.com"
}