pragma Singleton
import QtQuick 2.15

Item
{
    property color colorBrightText   : "#FFFFFF"
    property color colorLightText    : "#8E8EA9"
    property color colorLightText2   : "#8A8AA0"
    property color colorLightText3   : "#666687"
    property color colorBasePurple   : "#946BDE"
    property color colorMediumPurple : "#D9D8FF"
    property color colorPinkPurple   : "#E3D6FF"
    property color colorLightPurple  : "#F0F0FF"
    property color colorLightPurple2 : "#EEE9F1"
    property color colorBaseGray     : "#D2D2D2"
    property color colorDarkGray     : "#737373"
    property color colorLightGray    : "#F6F6F9"
    property color colorLightGray2   : "#EDEDED"
    property color colorLightGray3   : "#E2E2E2"
    property color colorNeonBlue     : "#4945FF"
    property color colorLightGreen   : "#EAFBE7"
    property color colorLightGreen2  : "#C6F0C2"
    property color colorMediumGreen  : "#5CB176"
    property color colorBaseRed      : "#D84B4D"
    property color colorCoffeeBrown  : "#E79535"
    property color colorBaseText     : "#32324D"
    property color colorBaseTitle    : "#4A4A6A"
    property color colorMediumText   : "#505057"
    property color colorLightBorder  : "#DCDCE4"
    property color colorLightBorder2 : "#C0C0CF"
    property color colorLightBorder3 : "#E0E0DE"
    property color colorDarkBorder   : "#ADADB4"
    property color colorError        : "#DC4446"
    property color colorBackground   : "#FFFFFF"
    property color darkBackground    : "#CCCCCC"
    property color colorSidebarMark  : "#F0F0FF"
    property color colorSeparator    : "#EAEAEF"
    property color loginWindowBackground  : "#efefef"
    property color loginContentBackground : "white"
    property color colorLightGrayBackground : "#EAEAEF"
    property color pagesBackground: "#F6F6F9"
    
    property string defaultFontFamily : "SF Pro Display"
}